import praw
import pandas as pd

bot_replies = [
	"Wow, I never would have guessed that lichess is good and chesscom is bad. Thanks for enlightening me.",
	"I'm glad you have such strong feelings about the relative merits of online chess platforms.",
	"Wow, it's always refreshing to hear a well-informed and nuanced opinion on the subject of lichess vs. chesscom.",
	"Wow, I'm really glad you took the time to share your unique perspective on the lichess vs. chesscom debate.",
	"I'm glad you're so passionate about the differences between lichess and chesscom. Your insight is truly invaluable.",
	"Wow, I've never heard anyone express such a strong opinion on the lichess vs. chesscom debate. You truly are a trailblazer.",
	"It's always refreshing to see someone so well-informed about the intricacies of online chess platforms.",
	"I'm glad that you have a strong opinion on online chess, now if you could only improve your chess skills.",
	"I'm impressed by your extensive knowledge about online chess platforms, now if you could only use it for good and not for evil.",
	"Wow, your opinion on lichess vs. chesscom is so strong that it could move mountains, unfortunately, it won't move your chess pieces.",
	"I'm glad you're so passionate about the differences between lichess and chesscom, now if you could only put that passion in studying chess openings.",
	"Wow, you're a true expert on the lichess vs. chesscom debate, now if you could only apply that knowledge to a real chess board.",
	"It's always good to see someone so well-informed about the intricacies of online chess platforms, now if you could only use that knowledge to beat me in a game of chess.",
	"I'm glad you're so invested in the lichess vs. chesscom debate, now if you could only invest that time in studying chess tactics.",
	"Wow, your opinion on lichess vs. chesscom is so strong, I'm sure it could survive a game of bullet chess.",
	"I'm glad you're so passionate about the differences between lichess and chesscom, now if you could only put that passion in studying chess endgames.",
	"Wow, you're a true expert on the lichess vs. chesscom debate, now if you could only apply that knowledge to beat a grandmaster in chess.",
	"It's always good to see someone so well-informed about the intricacies of online chess platforms, now if you could only use that knowledge to beat a computer at chess.",
	"I'm glad you're so invested in the lichess vs. chesscom debate, now if you could only invest that time in studying chess openings.",
	"Wow, your opinion on lichess vs. chesscom is so strong, I'm sure it could survive a game of blitz chess.",
	"I'm glad you're so passionate about the differences between lichess and chesscom, now if you could only put that passion in studying chess strategy.",
	"It's always good to see someone so well-informed about the intricacies of online chess platforms, now if you could only use that knowledge to beat a chess engine.",
	"I'm glad you're so invested in the lichess vs. chesscom debate, now if you could only invest that time in studying chess endgames.",
	"Wow, your opinion on lichess vs. chesscom is so strong, I'm sure it could survive a game of rapid chess.",
	"I'm glad you're so passionate about the differences between lichess and chesscom, now if you could only put that passion in studying chess openings.",
	"Lichess is like a fine wine, it only gets better with age. Chesscom is like a cheap beer, it's always the same old thing.",
	"Comparing lichess and chesscom is like choosing between a Ferrari and a Pinto, one is sleek and impressive, the other is just...there.",
	"Your love for lichess is like a warm hug from your grandma, comforting and familiar. Your disdain for chesscom is like a cold shoulder from your ex, icy and distant.",
	"Lichess is like a gourmet meal, it takes time to prepare but it's worth the wait. Chesscom is like a fast food burger, it's quick and easy but ultimately unsatisfying.",
	"Your opinion on lichess and chesscom is like a choose your own adventure book, one path leads to glory and the other leads to disappointment.",
	"Lichess is like a best friend, always there for you when you need it. Chesscom is like a frenemy, always trying to one up you.",
	"Comparing lichess and chesscom is like trying to choose between a puppy and a kitten, both are cute but one just speaks to you more.",
	"Your love for lichess is like a warm blanket on a cold day, comforting and cozy. Your hatred for chesscom is like a wet blanket at a bonfire, dampening the mood.",
	"Lichess is like a favorite song, it never gets old. Chesscom is like an elevator muzak, it's just background noise.",
	"Your opinion on lichess and chesscom is like a box of chocolates, you never know what you're gonna get.",
	"Wow, you must be a real chess pro to have such a strong opinion on lichess and chesscom.",
	"I'm impressed, you must have spent hours playing both lichess and chesscom to come to such a well-informed conclusion.",
	"I see you're an expert on all things chess, do you also have strong opinions on which brand of chess pieces is superior?",
	"I'm sure your opinion on lichess and chesscom is just as valuable as your chess rating.",
	"I'm glad you've taken the time to thoroughly research and evaluate both lichess and chesscom, now you can finally rest easy knowing you've made the best choice.",
  "I'm sure your extensive knowledge of chess strategy extends to your ability to distinguish between lichess and chesscom",
	"I'm glad you've finally found the one true chess platform, I'm sure the rest of us will all be converting to your way of thinking.",
	"Wow, you must be a real chess pro to have such a strong opinion on lichess and chesscom. Maybe you should stick to solving puzzles and leave the big decisions to the experts.",
	"I see you're an expert on all things chess, do you also have strong opinions on which color chess board is superior?",
	"I'm glad you've taken the time to thoroughly research and evaluate both lichess and chesscom, now you can finally rest easy knowing you've made the best choice.",
  "Wow, jumping on the lichess bandwagon, are we? I hope you at least did your own research and not just following the crowd.",
	"I see you're a fan of the trendy choice, lichess. How original.",
	"I'm glad you're finally jumping on the lichess bandwagon, I was starting to worry you were still stuck in the stone age using chesscom",
	"Welcome to the lichess fan club, I'm sure you'll fit right in with the rest of the sheep.",
	"I'm impressed you were able to tear yourself away from chesscom long enough to try out the popular choice, lichess.",
	"I see you're a follower of trends, not a leader. That's why you're on lichess now.",
	"I'm glad you've finally seen the light and joined the lichess crowd, better late than never I suppose.",
	"I see you're a fan of jumping on the lichess bandwagon, I hope you at least made an informed decision and not just following the crowd.",
	"I'm glad you're finally jumping on the lichess bandwagon, I was starting to worry you were still stuck in the stone age using chesscom",
	"Welcome to the lichess fan club, where being a follower is the norm.",
	"Looks like chesscom just got served by lichess, check and mate!",
	"I see you're a lichess fan, you must have a lot of free time on your hands.",
	"I'm glad you've finally seen the error of your ways and joined the lichess team.",
  "I see you've traded in your chesscom account for a shiny new lichess one, upgrade much?",
	"Looks like lichess just won another convert, chesscom must be shaking in their boots.",
	"I see you've upgraded to the superior platform, lichess. chesscom must be feeling inferior.",
	"Looks like another win for lichess and another loss for chesscom, the score speaks for itself.",
	"You must be a pro at chess by now, with all the time you spend on lichess. Or maybe you're just good at clicking buttons.",
	"Looks like someone's been hitting the lichess hard. I hope you're not neglecting your real-life responsibilities.",
	"I'm glad to see you've found your true passion in life: trash talking chesscom.",
	"Looks like someone's found their new favorite pastime: bashing chesscom and praising lichess. Must be nice to have such a clear-cut worldview.",
	"Wow, you really know how to lay it on thick when it comes to hating chesscom and loving lichess. I'm impressed.",
	"I'm sure lichess is thrilled to have such a vocal supporter. Keep up the good work.",
	"Looks like someone's found the ultimate outlet for their chess-related frustrations: bashing chesscom",
	"Looks like someone's a lichess fanatic. I hope you're not neglecting other important aspects of your life.",
	"I see you've found the one true way of playing chess: on lichess. I'll be sure to let the chesscom folks know."
]	
reply_length = len(bot_replies)

main_reply = 'As always: lichess good, chesscom bad !!!'